on:
  release:
    types: [created]

jobs:
  extension-release:
    uses: codefori/.github/.github/workflows/release.yaml@main
    secrets: inherit

  cli-release:
    name: Release rpglint CLI
    needs: extension-release
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for OIDC
      contents: write
    steps:
      - name: Use Node.js 24
        uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'

      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Update version number
        working-directory: cli/rpglint
        run: npm version --allow-same-version --no-git-tag-version ${{ github.ref_name }}

      - name: Install extension dependencies
        run: npm ci

      - name: Install CLI dependencies
        working-directory: cli/rpglint
        run: npm ci

      - name: Create build
        working-directory: cli/rpglint
        run: npm run webpack

      - name: Publish to npm
        working-directory: cli/rpglint
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Commit changes and move release tag
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git commit --allow-empty -a -m "Release ${{ github.ref_name }}"
          git tag -f ${{ github.ref_name }}
          git push --tags --force

      - name: Bump version number for next cycle
        working-directory: cli/rpglint
        run: npm version --no-git-tag-version prerelease --preid dev

      - name: Read new version
        id: new-version
        uses: beaconbrigade/package-json-version@v0.3
        with:
          path: cli/rpglint

      - name: Commit version number change
        run: |
          git commit -a -m "Starting ${{ steps.new-version.outputs.version }} development"
          git push
