on:
  pull_request:
    paths:
      - 'language/**'
      - 'tests/**'
    
jobs:
  release:
    name: Test runner
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 24
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
          submodules: true

      - name: Install dependencies
        run: npm install
          
      - name: Run ESLint
        run: node ./node_modules/eslint/bin/eslint src/** --no-error-on-unmatched-pattern

      - name: Run tests
        run: npm run test